### ISSUE TITLE
Criação de pagina sobre

### ISSUE THREAD

**Issue by ellismar** [elrsnt/github-master#3]
Criação de pagina sobre

**Comment by elrsnt** [comment]
Está em produção.

**Comment by ellismar** [comment]
Obrigado estou no aguardo.

________________________________
De: elrsnt <notifications@github.com>
Enviado: quarta-feira, 10 de julho de 2019 23:18
Para: elrsnt/github-master
Cc: ellismar; Author
Assunto: Re: [elrsnt/github-master] Criação de pagina sobre (#3)


Está em produção.

**Comment by ellismar** [comment]
Obrigado estou aguardando.

________________________________
De: elrsnt <notifications@github.com>
Enviado: quarta-feira, 10 de julho de 2019 23:18
Para: elrsnt/github-master
Cc: ellismar; Author
Assunto: Re: [elrsnt/github-master] Criação de pagina sobre (#3)


Está em produção.
